import os
import csv
import re
import time
from datetime import datetime
from PyQt6.QtCore import QThread, pyqtSignal

class SocketCANToAnyWriter:
    def __init__(self, output_file, output_type):
        self.output_file = output_file
        self.output_type = output_type
        self.f = None
        self.mdf = None
        self.bus_map = {}
        self.bus_count = 0
        self.msg_count = 0
        self.first_timestamp = None

    def __enter__(self):
        if self.output_type != "MF4 Log .mf4":
            self.f = open(self.output_file, "w")
        return self
        
    def _write_header(self, start_ts):
        if self.output_type in ["Kvaser .asc", "Motec CAN Inspector .asc", "Racelogic .asc"]:
            try:
                from datetime import datetime
                dt = datetime.fromtimestamp(start_ts)
                now_str = dt.strftime("%a %b %d %H:%M:%S %Y")
            except Exception:
                from datetime import datetime
                now_str = datetime.now().strftime("%a %b %d %H:%M:%S %Y")
            self.f.write(f"date {now_str}\n")
            self.f.write("base hex  timestamps absolute\n")
            self.f.write("Begin Triggerblock\n")
        elif self.output_type == "Pcan .trc":
            ole_time = (start_ts / 86400.0) + 25569.0
            from datetime import datetime
            import math
            try:
                dt_obj = datetime.fromtimestamp(start_ts)
                fractional_ms = int(math.modf(start_ts)[0] * 10000) / 10.0
                dt_str = dt_obj.strftime("%m/%d/%Y %H:%M:%S.%f")[:-3] + ".0"
            except:
                dt_str = "N/A"
            self.f.write(";$FILEVERSION=2.1\n")
            self.f.write(f";$STARTTIME={ole_time:.10f}\n")
            self.f.write(";$COLUMNS=N,O,T,B,I,d,L,D\n")
            self.f.write(";\n")
            self.f.write(f";   Start time: {dt_str}\n")
            self.f.write(";   Generated by Raw Log File Converter\n")
            self.f.write(";   Message   Time    Type Bus  ID      Rx/Tx\n")
            self.f.write(";   Number    Offset  |    |    [hex]   |  Data Length\n")
            self.f.write(";   |         [ms]    |    |    |       |  |  Data [hex] ...\n")
            self.f.write(";   |         |       |    |    |       |  |  |\n")
        elif self.output_type == "Busmaster .log":
            self.f.write("*** BUSMASTER Ver 3.2.2 ***\n")
            self.f.write("*** PROTOCOL CAN ***\n")
            self.f.write("*\n*\n*\n")
            try:
                from datetime import datetime
                dt = datetime.fromtimestamp(start_ts)
                self.f.write(f"***START DATE AND TIME {dt.day}:{dt.month}:{dt.year} {dt.hour}:{dt.minute}:{dt.second}:{int(dt.microsecond/1000)}***\n")
            except Exception:
                self.f.write("***     Log Start : 00:00:00 ***\n")
            self.f.write("***HEX***\n***SYSTEM MODE***\n***START CHANNEL BAUD RATE***\n***END CHANNEL BAUD RATE***\n***START DATABASE FILES***\n***END DATABASE FILES***\n")
            self.f.write("***<Time><Tx/Rx><Channel><CAN ID><Type><DLC><DataBytes>***\n")
        elif self.output_type == "CSS .csv":
            self.f.write("TimestampEpoch;BusChannel;ID;IDE;DLC;DataLength;DataBytes;RTR;BRS;ESI;Dir;FDF\n")
        elif self.output_type == "CSS CLx000 .txt":
            try:
                from datetime import datetime
                dt = datetime.fromtimestamp(start_ts)
                header_time = f"{dt.year:04d}{dt.month:02d}{dt.day:02d}T{dt.hour:02d}{dt.minute:02d}{dt.second:02d}"
            except Exception:
                header_time = "20230101T000000"
            self.f.write(f"# Time: {header_time}\n")
            self.f.write("# Value separator: \";\"\n")
            self.f.write("# Time format: 4\n")
            self.f.write("# Time separator: \"\"\n")
            self.f.write("# Time and date separator: \"T\"\n")
            self.f.write("Timestamp;Type;ID;Data\n")

    def write(self, line):
        if not line.startswith('('): return

        parts = line.strip().split(' ')
        if len(parts) < 3: return

        ts_str = parts[0].strip('()')
        try:
            timestamp = float(ts_str)
        except: return
        
        bus_str = parts[1]
        if bus_str not in self.bus_map:
            self.bus_map[bus_str] = self.bus_count
            self.bus_count += 1
        mapped_bus = self.bus_map[bus_str]
        
        frame_part = parts[2]
        if '#' not in frame_part: return
        id_str, data_part = frame_part.split('#')
        
        can_id = int(id_str, 16)
        is_ext = len(id_str) > 4
        
        is_rtr = False
        dlc = 0
        data_bytes = []
        
        if data_part.startswith('R'):
            is_rtr = True
            try: dlc = int(data_part[1:])
            except: dlc = 0
        else:
            dlc = len(data_part) // 2
            data_bytes = [int(data_part[i:i+2], 16) for i in range(0, len(data_part), 2)]
            is_rtr = False
            
        if self.first_timestamp is None:
            self.first_timestamp = timestamp
            if self.f is not None:
                self._write_header(timestamp)
                
        time_offset = (timestamp - self.first_timestamp) * 1000.0
        relative_s = timestamp - self.first_timestamp

        if self.output_type == "MF4 Log .mf4":
            # This branch is handled in __exit__ for MF4
            pass
        elif self.output_type == "SocketCAN .log":
            bus_out = f"can{mapped_bus}"
            id_fmt = f"{can_id:08X}" if is_ext else f"{can_id:03X}"
            data_str = f"R{dlc}" if is_rtr else "".join(f"{b:02X}" for b in data_bytes)
            self.f.write(f"({timestamp:.6f}) {bus_out} {id_fmt}#{data_str}\n")
        elif self.output_type in ["Kvaser .asc", "Motec CAN Inspector .asc", "Racelogic .asc"]:
            bus_out = str(mapped_bus + 1)
            id_fmt = f"{can_id:08X}x" if is_ext else f"{can_id:X}"
            if is_rtr:
                self.f.write(f"  {relative_s:.6f} {bus_out}  {id_fmt}             Rx   r {dlc}\n")
            else:
                data_str = " ".join([f"{b:02X}" for b in data_bytes])
                self.f.write(f"  {relative_s:.6f} {bus_out}  {id_fmt}             Rx   d {dlc} {data_str}\n")
        elif self.output_type == "Pcan .trc":
            self.msg_count += 1
            bus_out = str(mapped_bus + 1)
            id_fmt = f"{can_id:08X}" if is_ext else f"{can_id:04X}"
            data_str = " ".join(f"{b:02X}" for b in data_bytes)
            if is_rtr:
                self.f.write(f"{self.msg_count:>7} {time_offset:>13.3f} RR {bus_out:<5} {id_fmt} Rx {dlc}\n")
            else:
                self.f.write(f"{self.msg_count:>7} {time_offset:>13.3f} DT {bus_out:<5} {id_fmt} Rx {dlc:>4}    {data_str}\n")
        elif self.output_type == "Busmaster .log":
            bus_out = str(mapped_bus + 1)
            try:
                dt = datetime.fromtimestamp(timestamp)
                time_str = f"{dt.hour:02d}:{dt.minute:02d}:{dt.second:02d}:{int(dt.microsecond/100):04d}"
            except Exception:
                h = int((timestamp // 3600) % 24)
                m = int((timestamp // 60) % 60)
                s = int(timestamp % 60)
                f = int((timestamp % 1) * 10000)
                time_str = f"{h:02d}:{m:02d}:{s:02d}:{f:04d}"
                
            dir_str = "Rx"
            id_fmt = f"0x{can_id:X}"
            fmt_char = "s" if not is_ext else "x"
            if is_rtr:
                fmt_char += "r"
                
            data_str = " ".join([f"{b:02X}" for b in data_bytes])
            if data_str:
                self.f.write(f"{time_str} {dir_str} {bus_out} {id_fmt} {fmt_char} {dlc} {data_str}\n")
            else:
                self.f.write(f"{time_str} {dir_str} {bus_out} {id_fmt} {fmt_char} {dlc}\n")
        elif self.output_type == "CSS .csv":
            ide = "1" if is_ext else "0"
            rtr = "1" if is_rtr else "0"
            id_fmt = f"{can_id:08X}" if is_ext else f"{can_id:03X}"
            data_str = "".join([f"{b:02X}" for b in data_bytes])
            bus_channel = str(mapped_bus + 1)
            self.f.write(f"{timestamp:.6f};{bus_channel};{id_fmt};{ide};{dlc};{dlc};{data_str};{rtr};0;0;Rx;0\n")
        elif self.output_type == "RaceKeeper .csv":
            ts_int = int(timestamp * 1000)
            bus_label = "CAN" if mapped_bus == 0 else f"CAN{mapped_bus + 1}"
            id_fmt = f"{can_id:03X}" if not is_ext else f"{can_id:08X}"
            if is_rtr:
                self.f.write(f"{ts_int},{bus_label},{id_fmt}\n")
            else:
                data_str = ",".join([str(b) for b in data_bytes])
                if data_str:
                    self.f.write(f"{ts_int},{bus_label},{id_fmt},{data_str}\n")
                else:
                    self.f.write(f"{ts_int},{bus_label},{id_fmt}\n")
        elif self.output_type == "CSS CLx000 .txt":
            try:
                from datetime import datetime
                dt = datetime.fromtimestamp(timestamp)
                day_str = f"{dt.day:02d}T{dt.hour:02d}{dt.minute:02d}{dt.second:02d}{int(dt.microsecond/1000):03d}"
            except Exception:
                day_str = f"01T000000000"
            
            bus_type = str(mapped_bus + 1)
            id_fmt = f"{can_id:08X}" if is_ext else f"{can_id:03X}"
            if is_rtr:
                data_str = "R" + str(dlc)
            else:
                data_str = "".join([f"{b:02X}" for b in data_bytes]).lower()
            self.f.write(f"{day_str};{bus_type};{id_fmt};{data_str}\n")

    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_type is None and self.output_type == "MF4 Log .mf4":
            self._write_mf4()
        if self.f:
            self.f.close()

    def _write_mf4(self):
        try:
            import asammdf
            import numpy as np
        except ImportError:
            raise ImportError("asammdf or numpy is not installed.")
            
        if not self.frames:
            return
            
        timestamps = np.array([f[0] for f in self.frames], dtype=np.float64)
        buses = np.array([f[1] + 1 for f in self.frames], dtype=np.uint8)
        ids = np.array([f[2] for f in self.frames], dtype=np.uint32)
        ides = np.array([1 if f[3] else 0 for f in self.frames], dtype=np.uint8)
        rtrs = np.array([1 if f[4] else 0 for f in self.frames], dtype=np.uint8)
        dlcs = np.array([f[5] for f in self.frames], dtype=np.uint8)
        
        max_dlc = max(dlcs) if dlcs.size > 0 else 8
        data_arr = []
        for f in self.frames:
            b = f[6]
            padded = b + [0]*(max_dlc - len(b))
            data_arr.append(padded)
        if not data_arr:
            data_arr = [[]]
        data_bytes = np.array(data_arr, dtype=np.uint8)
        
        signals = [
            asammdf.Signal(samples=ids, timestamps=timestamps, name="CAN_DataFrame.ID"),
            asammdf.Signal(samples=data_bytes, timestamps=timestamps, name="CAN_DataFrame.DataBytes"),
            asammdf.Signal(samples=buses, timestamps=timestamps, name="CAN_DataFrame.BusChannel"),
            asammdf.Signal(samples=ides, timestamps=timestamps, name="CAN_DataFrame.IDE"),
            asammdf.Signal(samples=dlcs, timestamps=timestamps, name="CAN_DataFrame.DLC"),
            asammdf.Signal(samples=rtrs, timestamps=timestamps, name="CAN_DataFrame.RTR"),
        ]
        
        mdf = asammdf.MDF()
        mdf.append(signals, common_timebase=True)
        mdf.save(self.output_file)

class ConversionWorker(QThread):
    progress_update = pyqtSignal(int)
    status_update = pyqtSignal(str)
    finished = pyqtSignal()
    error = pyqtSignal(str)
    file_in_use_signal = pyqtSignal(str)

    def __init__(self, input_files, input_type, output_type):
        super().__init__()
        self.input_files = input_files
        self.input_type = input_type
        self.output_type = output_type

    def run(self):
        try:
            self.total_bytes = sum(os.path.getsize(f) for f in self.input_files)
            self.bytes_read_total = 0
            self._last_emitted_pct = -1

            for input_file in self.input_files:
                self.input_file = input_file
                base, _ = os.path.splitext(self.input_file)
                
                out_ext = ".log"
                if self.output_type in ["Kvaser .asc", "Motec CAN Inspector .asc", "Racelogic .asc"]: out_ext = ".asc"
                elif self.output_type == "Pcan .trc": out_ext = ".trc"
                elif self.output_type == "MF4 Log .mf4": out_ext = ".mf4"
                elif self.output_type in ["CSS .csv", "RaceKeeper .csv"]: out_ext = ".csv"
                
                self.output_file = f"{base}_out{out_ext}"

                # Test if file is in use
                try:
                    with open(self.input_file, 'a'): pass
                except IOError:
                    self.file_in_use_signal.emit(self.input_file)
                    continue

                # Switch based on type
                if self.input_type == "Pcan .trc":
                    self.convert_pcan_trc()
                elif self.input_type == "CSS CLx000 .txt":
                    self.convert_css_txt()
                elif self.input_type == "MF4 Log .mf4":
                    self.convert_mf4_log()
                elif self.input_type == "Busmaster .log":
                    self.convert_busmaster_log()
                elif self.input_type in ("Motec CAN Inspector .asc", "Kvaser .asc", "Racelogic .asc"):
                    self.convert_vector_asc()
                elif self.input_type == "RaceKeeper .csv":
                    self.convert_racekeeper_csv()
                elif self.input_type == "SocketCAN .log":
                    self.convert_socketcan_log()
                else:
                    raise ValueError(f"Unknown input type: {self.input_type}")
                    
                self.bytes_read_total += os.path.getsize(self.input_file)

            self.finished.emit()
            
        except Exception as e:
            self.error.emit(str(e))

    def update_progress(self, current_file_bytes):
        if self.total_bytes > 0:
            total_current = self.bytes_read_total + current_file_bytes
            pct = int((total_current / self.total_bytes) * 100)
            pct = min(100, max(0, pct))
            if pct > self._last_emitted_pct:
                self.progress_update.emit(pct)
                self._last_emitted_pct = pct

    def convert_pcan_trc(self):
        with open(self.input_file, "r") as readfile, SocketCANToAnyWriter(self.output_file, self.output_type) as logfile:
            current_bytes = 0
            file_size = os.path.getsize(self.input_file)
            base_epoch = 0.0
            
            for line_raw in readfile:
                current_bytes += len(line_raw)
                if current_bytes % 32768 < 200:
                    self.update_progress(current_bytes)
                
                line = line_raw.strip().split()
                if not line:
                    continue
                if line[0].startswith(';'):
                    if 'STARTTIME=' in line_raw:
                        ole_time = float(line_raw.split('=')[1].strip())
                        base_epoch = (ole_time - 25569.0) * 86400.0
                    continue
                    
                if len(line) < 7:
                    continue
                    
                try:
                    timestamp = base_epoch + (float(line[1]) / 1000.0)
                    msg_type = line[2] 
                    bus_idx = line[3]
                    raw_id = line[4]
                    dlc = int(line[6])
                    
                    is_rtr = (msg_type == "RR")
                    is_ext = len(raw_id) > 4
                    can_id = int(raw_id, 16)
                    
                    if is_rtr:
                        data_str = f"R{dlc}"
                    else:
                        data_bytes = line[7 : 7 + dlc]
                        data_str = "".join([b.zfill(2).upper() for b in data_bytes])
                        
                    id_fmt = f"{can_id:08X}" if is_ext else f"{can_id:03X}"
                    can_if = f"can{int(bus_idx) - 1}"
                    
                    logfile.write(f"({timestamp:.6f}) {can_if} {id_fmt}#{data_str}\n")
                except Exception:
                    pass
            self.update_progress(file_size)

    def convert_css_csv(self):
        with open(self.input_file, "r") as readfile, SocketCANToAnyWriter(self.output_file, self.output_type) as logfile:
            # We can read line by line manually or use DictReader
            # Since DictReader caches the headers, we'll do manual size tracking 
            # by reading lines into DictReader.
            headers = None
            current_bytes = 0
            for line in readfile:
                current_bytes += len(line)
                self.update_progress(current_bytes)
                if not line.strip(): continue

                if not headers:
                    headers = line.strip().split(";")
                    continue

                parts = line.strip().split(";")
                if len(parts) < len(headers):
                    continue
                row = dict(zip(headers, parts))
                
                try:
                    ts = float(row.get("TimestampEpoch", 0))
                except ValueError: continue
                ts_str = f"{ts:.6f}"

                try:
                    bus_channel = int(row.get("BusChannel", 1))
                except ValueError: bus_channel = 1
                iface = f"can{max(0, bus_channel - 1)}"

                raw_id_str = row.get("ID", "").strip()
                ide = int(row.get("IDE", "0"))
                try:
                    can_id = int(raw_id_str, 16)
                except ValueError:
                    try: can_id = int(raw_id_str, 10)
                    except: can_id = 0

                if ide == 0:
                    can_id_str = f"{can_id:03X}"
                else:
                    can_id_str = f"{can_id:08X}"

                rtr = int(row.get("RTR", "0"))
                dlc_str = row.get("DLC", row.get("DataLength", "0"))
                dlc = int(dlc_str)
                data_hex = row.get("DataBytes", "").strip().upper()

                if rtr:
                    frame_part = f"{can_id_str}#R{dlc}"
                else:
                    frame_part = f"{can_id_str}#{data_hex}"

                logfile.write(f"({ts_str}) {iface} {frame_part}\n")

    def _datetime_to_timestamp(self, dt):
        epoch = datetime(1970, 1, 1)
        delta = dt - epoch
        return delta.total_seconds()

    def _custom_strptime(self, s, fmt):
        if fmt.endswith(':%f'):
            s = s[:-2] + '00' + s[-2:]
        return datetime.strptime(s, fmt)

    def convert_busmaster_log(self):
        with open(self.input_file, "r") as readfile, SocketCANToAnyWriter(self.output_file, self.output_type) as logfile:
            base_epoch = 0.0
            day_offset = 0.0
            last_secs = 0.0
            current_bytes = 0
            file_size = os.path.getsize(self.input_file)
            
            for line_raw in readfile:
                current_bytes += len(line_raw)
                if current_bytes % 32768 < 200:
                    self.update_progress(current_bytes)
                
                row = line_raw.strip().split()
                if not row: continue
                
                if line_raw.startswith("***START DATE AND TIME"):
                    try:
                        date_str = row[4] # 29:9:2023
                        dt_obj = datetime.strptime(date_str, "%d:%m:%Y")
                        base_epoch = dt_obj.timestamp()
                    except: pass
                    continue
                    
                if row[0].startswith('***') or row[0].startswith('*'): 
                    continue
                
                try:
                    ts_dt = self._custom_strptime(row[0], '%H:%M:%S:%f')
                    ts_secs = ts_dt.hour * 3600 + ts_dt.minute * 60 + ts_dt.second + ts_dt.microsecond / 1e6
                    if ts_secs < last_secs:
                        day_offset += 86400
                    last_secs = ts_secs
                    
                    timestamp = base_epoch + ts_secs + day_offset
                    
                    ch_str = row[2] if row[1] in ["Rx", "Tx"] else row[1]
                    try:
                        channel = int(ch_str) - 1
                    except ValueError:
                        channel = 0
                        
                    can_id = int(row[3], 0)
                    fmt_flag = row[4].lower() 
                    is_rtr = ('r' in fmt_flag)
                    is_ext = ('x' in fmt_flag)
                    dlc = int(row[5])
                    
                    id_fmt = f"{can_id:08X}" if is_ext else f"{can_id:03X}"
                    can_if = f"can{max(0, channel)}"
                    
                    if is_rtr:
                        data_str = f"R{dlc}"
                    else:
                        data_bytes = row[6 : 6 + dlc]
                        data_str = "".join([b.zfill(2).upper() for b in data_bytes])
                        
                    logfile.write(f"({timestamp:016.6f}) {can_if} {id_fmt}#{data_str}\n")
                except Exception:
                    pass
            self.update_progress(file_size)

    def convert_vector_asc(self):
        with open(self.input_file, "r") as readfile, SocketCANToAnyWriter(self.output_file, self.output_type) as logfile:
            current_bytes = 0
            file_size = os.path.getsize(self.input_file)
            base_epoch = 0.0
            
            for line_raw in readfile:
                current_bytes += len(line_raw)
                if current_bytes % 32768 < 200:
                    self.update_progress(current_bytes)
                
                line = line_raw.strip().split()
                if not line: continue
                
                if line[0] == "date":
                    try:
                        date_str = " ".join(line[1:])
                        from datetime import datetime
                        dt = None
                        formats = [
                            "%a %b %d %H:%M:%S %Y",
                            "%a %b %d %I:%M:%S %p %Y",
                            "%Y%m%d %H:%M:%S"
                        ]
                        for fmt in formats:
                            try:
                                dt = datetime.strptime(date_str.strip(), fmt)
                                break
                            except ValueError:
                                pass
                        if dt:
                            base_epoch = dt.timestamp()
                    except Exception: pass
                    continue
                    
                if len(line) < 6: continue
                if not line[0].replace('.', '', 1).isdigit():
                    continue
                
                try:
                    timestamp = base_epoch + float(line[0])
                    
                    is_canfd = False
                    idx = 1
                    if line[idx] == "CANFD":
                        is_canfd = True
                        idx += 1
                        
                    channel = int(line[idx])
                    idx += 1
                    
                    is_rtr = False
                    if is_canfd:
                        direction = line[idx]
                        idx += 1
                        raw_id = line[idx]
                        idx += 3 
                        dlc = int(line[idx])
                        idx += 1
                        data_len = int(line[idx])
                        idx += 1
                        data_bytes = line[idx:idx+data_len]
                    else:
                        raw_id = line[idx]
                        idx += 1
                        direction = line[idx]
                        idx += 1
                        frame_type = line[idx]
                        idx += 1
                        dlc = int(line[idx])
                        idx += 1
                        data_len = dlc
                        if frame_type == 'r':
                            is_rtr = True
                            data_bytes = []
                        else:
                            data_bytes = line[idx:idx+data_len]
                            
                    if raw_id.endswith("x"):
                        can_id = int(raw_id[:-1], 16)
                        id_fmt = f"{can_id:08X}"
                    else:
                        can_id = int(raw_id, 16)
                        id_fmt = f"{can_id:03X}"
                        
                    can_if = f"can{channel - 1}"
                    
                    if is_rtr:
                        data_str = f"R{dlc}"
                    else:
                        data_str = "".join([b.zfill(2).upper() for b in data_bytes])
                        
                    logfile.write(f"({timestamp:.6f}) {can_if} {id_fmt}#{data_str}\n")
                except Exception:
                    pass
            self.update_progress(file_size)

    def convert_racekeeper_csv(self):
        with open(self.input_file, "r") as readfile, SocketCANToAnyWriter(self.output_file, self.output_type) as logfile:
            lasttimestamp = 0.0
            incrementer = 0.0
            current_bytes = 0
            file_size = os.path.getsize(self.input_file)
            
            for line_raw in readfile:
                current_bytes += len(line_raw)
                if current_bytes % 32768 < 200:
                    self.update_progress(current_bytes)
                
                row = next(csv.reader([line_raw]), [])
                if len(row) < 4:
                    continue
                    
                bus_label = row[1].upper()
                if not bus_label.startswith('CAN'):
                    continue
                
                try:
                    timestamp = int(row[0])
                    can_id = int(row[2])
                    
                    ch_str = bus_label.replace('CAN', '')
                    channel = int(ch_str) - 1 if ch_str else 0
                    
                    data_fields = [int(val) for val in row[3:]]
                    data = ''.join([f'{val:02X}' for val in data_fields])
                    
                    if lasttimestamp != timestamp:
                        lasttimestamp = timestamp
                        incrementer = 0.0
                    else:
                        incrementer += 0.001
                        timestamp = timestamp + incrementer

                    id_fmt = f"{can_id:08X}" if can_id > 0x7FF else f"{can_id:03X}"
                    can_if = f"can{channel}"

                    logfile.write(f"({timestamp:016.6f}) {can_if} {id_fmt}#{data}\n")
                except Exception:
                    pass
            self.update_progress(file_size)

    def convert_socketcan_log(self):
        with open(self.input_file, "r") as readfile, SocketCANToAnyWriter(self.output_file, self.output_type) as logfile:
            current_bytes = 0
            file_size = os.path.getsize(self.input_file)
            for i, line in enumerate(readfile):
                current_bytes += len(line)
                if i % 1000 == 0:
                    self.update_progress(current_bytes)
                logfile.write(line)
            self.update_progress(file_size)

    def convert_mf4_log(self):
        try:
            import asammdf
        except ImportError:
            raise ImportError("The 'asammdf' module is required. Please install it using 'pip install asammdf'.")
            
        mdf = asammdf.MDF(self.input_file)
        
        with SocketCANToAnyWriter(self.output_file, self.output_type) as logfile:
            try:
                start_epoch = mdf.header.start_time.timestamp()
            except Exception:
                start_epoch = 0.0

            try:
                occurrences = mdf.whereis("CAN_DataFrame.ID")
                if not occurrences:
                    raise Exception("No 'CAN_DataFrame.ID' found in MF4 file.")
                
                # whereis returns tuple of (group_idx, channel_idx)
                group_indices = set(grp for grp, ch in occurrences)

                all_frames = []
                for grp in group_indices:
                    try:
                        ids_sig = mdf.get("CAN_DataFrame.ID", group=grp)
                        datas_sig = mdf.get("CAN_DataFrame.DataBytes", group=grp)
                        buses_sig = mdf.get("CAN_DataFrame.BusChannel", group=grp)
                        ides_sig = mdf.get("CAN_DataFrame.IDE", group=grp)
                        
                        try:
                            dlcs_sig = mdf.get("CAN_DataFrame.DataLength", group=grp)
                        except Exception:
                            try:
                                dlcs_sig = mdf.get("CAN_DataFrame.DLC", group=grp)
                            except Exception:
                                dlcs_sig = None
                                
                        try:
                            rtrs_sig = mdf.get("CAN_DataFrame.RTR", group=grp)
                            rtrs = rtrs_sig.samples
                        except Exception:
                            rtrs = [0] * len(ids_sig.samples)

                        timestamps = ids_sig.timestamps
                        ids = ids_sig.samples
                        datas = datas_sig.samples
                        buses = buses_sig.samples
                        ides = ides_sig.samples
                        
                        if dlcs_sig is not None:
                            dlcs = dlcs_sig.samples
                        else:
                            dlcs = [8] * len(ids)

                        total_len = len(timestamps)
                        for i in range(total_len):
                            ts = timestamps[i] + start_epoch
                            bus = int(buses[i])
                            
                            can_id = int(ids[i])
                            ide = int(ides[i])
                            can_id_str = f"{can_id:03X}" if ide == 0 else f"{can_id:08X}"
                                
                            dlc = int(dlcs[i])
                            rtr = int(rtrs[i])
                            
                            data_arr = datas[i]
                            data_hex = "".join([f"{b:02X}" for b in data_arr[:dlc]])
                            
                            if rtr:
                                frame_part = f"{can_id_str}#R{dlc}"
                            else:
                                frame_part = f"{can_id_str}#{data_hex}"

                            all_frames.append((ts, bus, frame_part))
                    except Exception as e:
                        print(f"Skipping group {grp} due to error: {e}")
                        continue
                
                # Sort all frames chronologically
                all_frames.sort(key=lambda x: x[0])
                
                total_frames = len(all_frames)
                if total_frames == 0:
                    raise Exception("No valid CAN frames found across any groups.")
                    
                # Dynamically map bus IDs starting at 0 (CAN1->0, CAN2->1, etc.)
                unique_buses = sorted(list(set([f[1] for f in all_frames])))
                bus_map = {bus_raw: idx for idx, bus_raw in enumerate(unique_buses)}

                # Write to output file and give progress
                for i, (ts, bus_raw, frame_part) in enumerate(all_frames):
                    if i % 10000 == 0:
                        self.update_progress(int((i / total_frames) * os.path.getsize(self.input_file)))
                        
                    iface = f"can{bus_map[bus_raw]}"
                    logfile.write(f"({ts:.6f}) {iface} {frame_part}\n")
                    
            except Exception as e:
                raise Exception(f"Failed to extract raw CAN data from multiple groups. Error: {e}")

    def convert_css_txt(self):
        with open(self.input_file, "r") as readfile, SocketCANToAnyWriter(self.output_file, self.output_type) as logfile:
            base_year_month = ""
            file_size = os.path.getsize(self.input_file)
            current_bytes = 0
            
            for line_raw in readfile:
                current_bytes += len(line_raw)
                if current_bytes % 32768 < 200:
                    self.update_progress(current_bytes)
                
                line_str = line_raw.strip()
                if line_str.startswith("# Time:"):
                    parts = line_str.split(" ")
                    if len(parts) > 2:
                        base_year_month = parts[2][:6]
                    else:
                        base_year_month = "202301"
                    continue
                if not line_str or line_str.startswith('#') or line_str.startswith('Timestamp'):
                    continue
                
                parts = line_str.split(';')
                if len(parts) < 4: continue
                
                try:
                    ts_str = parts[0]
                    from datetime import datetime
                    if base_year_month == "":
                        base_year_month = "202301"
                    dt_str = base_year_month + ts_str.replace("T", "")
                    
                    if len(dt_str) >= 14:
                        ms = float(dt_str[14:]) / 1000.0 if len(dt_str) > 14 else 0.0
                        dt = datetime.strptime(dt_str[:14], "%Y%m%d%H%M%S")
                        timestamp = dt.timestamp() + ms
                    else:
                        timestamp = 0.0
                    
                    bus_channel = int(parts[1]) - 1 if parts[1] else 0
                    can_id = int(parts[2], 16)
                    data_str = parts[3]
                    
                    id_fmt = f"{can_id:08X}" if can_id > 0x7FF else f"{can_id:03X}"
                    can_if = f"can{bus_channel}"
                    
                    logfile.write(f"({timestamp:.6f}) {can_if} {id_fmt}#{data_str.upper()}\n")
                except Exception:
                    pass
            self.update_progress(file_size)
